CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallets (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    address VARCHAR(255) NOT NULL,
    balance DECIMAL(28, 18) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (email) VALUES ('demo@ainexus.com');
INSERT INTO wallets (user_id, address, balance) VALUES (1, '0x742E4d6c9d6A5B6F6F6F6F6F6F6F6F6F6F6F6F6F', 248750.42);
